# Generated by Django 4.1.5 on 2023-02-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_iteminorder_order_iteminorder_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminorder',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
